version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=rafa
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres-e2e:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=db_e2e
      - POSTGRES_USER=e2e
      - POSTGRES_PASSWORD=e2e123
    ports:
      # use port 5434 to no conflict between DB but internal still uses 5432
      - 5434:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
